// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_EkzTJCKX3asJqAUyj_KeD-GoKQIvXs',
    appId: '1:73136527885:web:e4389bb2be83868b06d344',
    messagingSenderId: '73136527885',
    projectId: 'flutter-crud-firebase-e160c',
    authDomain: 'flutter-crud-firebase-e160c.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-e160c.firebasestorage.app',
    measurementId: 'G-M5DMM4SBZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzQB2PopCunH4J2tBWNNByy_Qh_xfsbU',
    appId: '1:73136527885:android:1904c072acd4ac6306d344',
    messagingSenderId: '73136527885',
    projectId: 'flutter-crud-firebase-e160c',
    storageBucket: 'flutter-crud-firebase-e160c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbQndHUlZEpkoRu_wUNAIQh2h5WFZ95qQ',
    appId: '1:73136527885:ios:198c686d6fdcb67706d344',
    messagingSenderId: '73136527885',
    projectId: 'flutter-crud-firebase-e160c',
    storageBucket: 'flutter-crud-firebase-e160c.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbQndHUlZEpkoRu_wUNAIQh2h5WFZ95qQ',
    appId: '1:73136527885:ios:198c686d6fdcb67706d344',
    messagingSenderId: '73136527885',
    projectId: 'flutter-crud-firebase-e160c',
    storageBucket: 'flutter-crud-firebase-e160c.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_EkzTJCKX3asJqAUyj_KeD-GoKQIvXs',
    appId: '1:73136527885:web:07b8645543308d2a06d344',
    messagingSenderId: '73136527885',
    projectId: 'flutter-crud-firebase-e160c',
    authDomain: 'flutter-crud-firebase-e160c.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-e160c.firebasestorage.app',
    measurementId: 'G-9H1SVGR6D9',
  );

}